name: simplewechat
version: 2
libraries:
- name: webpy
  version: "0.36"

- name: lxml
  version: "2.3.4"
cron:
    - description: update_recentoj
          url: /updatesql.py
          schedule: midnight
          timezone: Beijing